# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CallerInfo',
            new_name='CallerInfoQueue',
        ),
    ]
