# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0020_feedbackconfig_send_time_in_delta'),
        ('lexbot', '0003_auto_20180219_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceBotConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting_message', models.TextField(default='Welcome!')),
                ('use_audio', models.BooleanField(default=False)),
                ('greeting_voice', models.FileField(blank=True, null=True, upload_to='')),
                ('generalsettings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_settings.GeneralSettings')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
