# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 19:45
from __future__ import unicode_literals

from django.db import migrations


def up(apps, schema_editor):
    GeneralSettings = apps.get_model('app_settings', 'GeneralSettings')
    VoiceBotConfig = apps.get_model('lexbot', 'VoiceBotConfig')
    for g in GeneralSettings.objects.all():
        VoiceBotConfig.objects.get_or_create(generalsettings=g)


def down(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('lexbot', '0004_voicebotconfig'),
    ]

    operations = [
        migrations.RunPython(up, down),
    ]
