# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-02 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexbot', '0006_auto_20180222_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicebotconfig',
            name='greeting_message',
            field=models.TextField(default='Welcome! Press 1 to book an appointment,  press 2 to reschedule, press 3 to cancel, press 4 for all other questions.'),
        ),
    ]
