# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-04 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lexbot', '0007_auto_20180302_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicebotconfig',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voicebotconfig',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='voicebotconfig',
            name='greeting_message',
            field=models.TextField(default='Welcome to {company_name}! Press 1 to book an appointment,  press 2 to reschedule, press 3 to cancel, press 4 for all other questions.'),
        ),
    ]
