# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-15 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lexbot', '0008_auto_20180304_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callerinfoqueue',
            name='generalsettings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_settings.GeneralSettings'),
        ),
    ]
