# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-16 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lexbot', '0009_auto_20180415_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callerinfoqueue',
            name='generalsettings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_settings.GeneralSettings'),
        ),
    ]
