# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-16 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexbot', '0010_auto_20180416_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callerinfoqueue',
            name='caller_country',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
