# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-22 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lexbot', '0011_auto_20180416_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='LexSessionAttrsStore',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_id', models.CharField(db_index=True, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('attrs', models.TextField(null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
