# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-05 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexbot', '0012_lexsessionattrsstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='callerinfoqueue',
            name='user_choice',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
