# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-24 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexbot', '0013_callerinfoqueue_user_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='callerinfoqueue',
            name='provider_number',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
    ]
