# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-01 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexbot', '0015_auto_20181026_0353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LexSessionAttrsStore',
        ),
    ]
