export const countriesList = [
  {'code': 'af', 'nicename': 'Afghanistan', 'phonecode': 93, 'id': 0},
  {'code': 'al', 'nicename': 'Albania', 'phonecode': 355, 'id': 1},
  {'code': 'dz', 'nicename': 'Algeria', 'phonecode': 213, 'id': 2},
  {'code': 'as', 'nicename': 'American Samoa', 'phonecode': 1684, 'id': 3},
  {'code': 'ad', 'nicename': 'Andorra', 'phonecode': 376, 'id': 4},
  {'code': 'ao', 'nicename': 'Angola', 'phonecode': 244, 'id': 5},
  {'code': 'ai', 'nicename': 'Anguilla', 'phonecode': 1264, 'id': 6},
  {'code': 'aq', 'nicename': 'Antarctica', 'phonecode': 0, 'id': 7},
  {'code': 'ag', 'nicename': 'Antigua and Barbuda', 'phonecode': 1268, 'id': 8},
  {'code': 'ar', 'nicename': 'Argentina', 'phonecode': 54, 'id': 9},
  {'code': 'am', 'nicename': 'Armenia', 'phonecode': 374, 'id': 10},
  {'code': 'aw', 'nicename': 'Aruba', 'phonecode': 297, 'id': 11},
  {'code': 'au', 'nicename': 'Australia', 'phonecode': 61, 'id': 12},
  {'code': 'at', 'nicename': 'Austria', 'phonecode': 43, 'id': 13},
  {'code': 'az', 'nicename': 'Azerbaijan', 'phonecode': 994, 'id': 14},
  {'code': 'bs', 'nicename': 'Bahamas', 'phonecode': 1242, 'id': 15},
  {'code': 'bh', 'nicename': 'Bahrain', 'phonecode': 973, 'id': 16},
  {'code': 'bd', 'nicename': 'Bangladesh', 'phonecode': 880, 'id': 17},
  {'code': 'bb', 'nicename': 'Barbados', 'phonecode': 1246, 'id': 18},
  {'code': 'by', 'nicename': 'Belarus', 'phonecode': 375, 'id': 19},
  {'code': 'be', 'nicename': 'Belgium', 'phonecode': 32, 'id': 20},
  {'code': 'bz', 'nicename': 'Belize', 'phonecode': 501, 'id': 21},
  {'code': 'bj', 'nicename': 'Benin', 'phonecode': 229, 'id': 22},
  {'code': 'bm', 'nicename': 'Bermuda', 'phonecode': 1441, 'id': 23},
  {'code': 'bt', 'nicename': 'Bhutan', 'phonecode': 975, 'id': 24},
  {'code': 'bo', 'nicename': 'Bolivia', 'phonecode': 591, 'id': 25},
  {'code': 'ba', 'nicename': 'Bosnia and Herzegovina', 'phonecode': 387, 'id': 26},
  {'code': 'bw', 'nicename': 'Botswana', 'phonecode': 267, 'id': 27},
  {'code': 'bv', 'nicename': 'Bouvet Island', 'phonecode': 0, 'id': 28},
  {'code': 'br', 'nicename': 'Brazil', 'phonecode': 55, 'id': 29},
  {'code': 'io', 'nicename': 'British Indian Ocean Territory', 'phonecode': 246, 'id': 30},
  {'code': 'bn', 'nicename': 'Brunei Darussalam', 'phonecode': 673, 'id': 31},
  {'code': 'bg', 'nicename': 'Bulgaria', 'phonecode': 359, 'id': 32},
  {'code': 'bf', 'nicename': 'Burkina Faso', 'phonecode': 226, 'id': 33},
  {'code': 'bi', 'nicename': 'Burundi', 'phonecode': 257, 'id': 34},
  {'code': 'kh', 'nicename': 'Cambodia', 'phonecode': 855, 'id': 35},
  {'code': 'cm', 'nicename': 'Cameroon', 'phonecode': 237, 'id': 36},
  {'code': 'ca', 'nicename': 'Canada', 'phonecode': 1, 'id': 37},
  {'code': 'cv', 'nicename': 'Cape Verde', 'phonecode': 238, 'id': 38},
  {'code': 'ky', 'nicename': 'Cayman Islands', 'phonecode': 1345, 'id': 39},
  {'code': 'cf', 'nicename': 'Central African Republic', 'phonecode': 236, 'id': 40},
  {'code': 'td', 'nicename': 'Chad', 'phonecode': 235, 'id': 41},
  {'code': 'cl', 'nicename': 'Chile', 'phonecode': 56, 'id': 42},
  {'code': 'cn', 'nicename': 'China', 'phonecode': 86, 'id': 43},
  {'code': 'cx', 'nicename': 'Christmas Island', 'phonecode': 61, 'id': 44},
  {'code': 'cc', 'nicename': 'Cocos (Keeling) Islands', 'phonecode': 672, 'id': 45},
  {'code': 'co', 'nicename': 'Colombia', 'phonecode': 57, 'id': 46},
  {'code': 'km', 'nicename': 'Comoros', 'phonecode': 269, 'id': 47},
  {'code': 'cg', 'nicename': 'Congo', 'phonecode': 242, 'id': 48},
  {'code': 'cd', 'nicename': 'Congo, the Democratic Republic of the', 'phonecode': 242, 'id': 49},
  {'code': 'ck', 'nicename': 'Cook Islands', 'phonecode': 682, 'id': 50},
  {'code': 'cr', 'nicename': 'Costa Rica', 'phonecode': 506, 'id': 51},
  {'code': 'ci', 'nicename': 'Cote D\'\'Ivoire', 'phonecode': 225, 'id': 52},
  {'code': 'hr', 'nicename': 'Croatia', 'phonecode': 385, 'id': 53},
  {'code': 'cu', 'nicename': 'Cuba', 'phonecode': 53, 'id': 54},
  {'code': 'cy', 'nicename': 'Cyprus', 'phonecode': 357, 'id': 55},
  {'code': 'cz', 'nicename': 'Czech Republic', 'phonecode': 420, 'id': 56},
  {'code': 'dk', 'nicename': 'Denmark', 'phonecode': 45, 'id': 57},
  {'code': 'dj', 'nicename': 'Djibouti', 'phonecode': 253, 'id': 58},
  {'code': 'dm', 'nicename': 'Dominica', 'phonecode': 1767, 'id': 59},
  {'code': 'do', 'nicename': 'Dominican Republic', 'phonecode': 1809, 'id': 60},
  {'code': 'ec', 'nicename': 'Ecuador', 'phonecode': 593, 'id': 61},
  {'code': 'eg', 'nicename': 'Egypt', 'phonecode': 20, 'id': 62},
  {'code': 'sv', 'nicename': 'El Salvador', 'phonecode': 503, 'id': 63},
  {'code': 'gq', 'nicename': 'Equatorial Guinea', 'phonecode': 240, 'id': 64},
  {'code': 'er', 'nicename': 'Eritrea', 'phonecode': 291, 'id': 65},
  {'code': 'ee', 'nicename': 'Estonia', 'phonecode': 372, 'id': 66},
  {'code': 'et', 'nicename': 'Ethiopia', 'phonecode': 251, 'id': 67},
  {'code': 'fk', 'nicename': 'Falkland Islands (Malvinas)', 'phonecode': 500, 'id': 68},
  {'code': 'fo', 'nicename': 'Faroe Islands', 'phonecode': 298, 'id': 69},
  {'code': 'fj', 'nicename': 'Fiji', 'phonecode': 679, 'id': 70},
  {'code': 'fi', 'nicename': 'Finland', 'phonecode': 358, 'id': 71},
  {'code': 'fr', 'nicename': 'France', 'phonecode': 33, 'id': 72},
  {'code': 'gf', 'nicename': 'French Guiana', 'phonecode': 594, 'id': 73},
  {'code': 'pf', 'nicename': 'French Polynesia', 'phonecode': 689, 'id': 74},
  {'code': 'tf', 'nicename': 'French Southern Territories', 'phonecode': 0, 'id': 75},
  {'code': 'ga', 'nicename': 'Gabon', 'phonecode': 241, 'id': 76},
  {'code': 'gm', 'nicename': 'Gambia', 'phonecode': 220, 'id': 77},
  {'code': 'ge', 'nicename': 'Georgia', 'phonecode': 995, 'id': 78},
  {'code': 'de', 'nicename': 'Germany', 'phonecode': 49, 'id': 79},
  {'code': 'gh', 'nicename': 'Ghana', 'phonecode': 233, 'id': 80},
  {'code': 'gi', 'nicename': 'Gibraltar', 'phonecode': 350, 'id': 81},
  {'code': 'gr', 'nicename': 'Greece', 'phonecode': 30, 'id': 82},
  {'code': 'gl', 'nicename': 'Greenland', 'phonecode': 299, 'id': 83},
  {'code': 'gd', 'nicename': 'Grenada', 'phonecode': 1473, 'id': 84},
  {'code': 'gp', 'nicename': 'Guadeloupe', 'phonecode': 590, 'id': 85},
  {'code': 'gu', 'nicename': 'Guam', 'phonecode': 1671, 'id': 86},
  {'code': 'gt', 'nicename': 'Guatemala', 'phonecode': 502, 'id': 87},
  {'code': 'gn', 'nicename': 'Guinea', 'phonecode': 224, 'id': 88},
  {'code': 'gw', 'nicename': 'Guinea-Bissau', 'phonecode': 245, 'id': 89},
  {'code': 'gy', 'nicename': 'Guyana', 'phonecode': 592, 'id': 90},
  {'code': 'ht', 'nicename': 'Haiti', 'phonecode': 509, 'id': 91},
  {'code': 'hm', 'nicename': 'Heard Island and Mcdonald Islands', 'phonecode': 0, 'id': 92},
  {'code': 'va', 'nicename': 'Holy See (Vatican City State)', 'phonecode': 39, 'id': 93},
  {'code': 'hn', 'nicename': 'Honduras', 'phonecode': 504, 'id': 94},
  {'code': 'hk', 'nicename': 'Hong Kong', 'phonecode': 852, 'id': 95},
  {'code': 'hu', 'nicename': 'Hungary', 'phonecode': 36, 'id': 96},
  {'code': 'is', 'nicename': 'Iceland', 'phonecode': 354, 'id': 97},
  {'code': 'in', 'nicename': 'India', 'phonecode': 91, 'id': 98},
  {'code': 'id', 'nicename': 'Indonesia', 'phonecode': 62, 'id': 99},
  {'code': 'ir', 'nicename': 'Iran, Islamic Republic of', 'phonecode': 98, 'id': 100},
  {'code': 'iq', 'nicename': 'Iraq', 'phonecode': 964, 'id': 101},
  {'code': 'ie', 'nicename': 'Ireland', 'phonecode': 353, 'id': 102},
  {'code': 'il', 'nicename': 'Israel', 'phonecode': 972, 'id': 103},
  {'code': 'it', 'nicename': 'Italy', 'phonecode': 39, 'id': 104},
  {'code': 'jm', 'nicename': 'Jamaica', 'phonecode': 1876, 'id': 105},
  {'code': 'jp', 'nicename': 'Japan', 'phonecode': 81, 'id': 106},
  {'code': 'jo', 'nicename': 'Jordan', 'phonecode': 962, 'id': 107},
  {'code': 'kz', 'nicename': 'Kazakhstan', 'phonecode': 7, 'id': 108},
  {'code': 'ke', 'nicename': 'Kenya', 'phonecode': 254, 'id': 109},
  {'code': 'ki', 'nicename': 'Kiribati', 'phonecode': 686, 'id': 110},
  {'code': 'kp', 'nicename': 'Korea, Democratic People\'\'s Republic of', 'phonecode': 850, 'id': 111},
  {'code': 'kr', 'nicename': 'Korea, Republic of', 'phonecode': 82, 'id': 112},
  {'code': 'kw', 'nicename': 'Kuwait', 'phonecode': 965, 'id': 113},
  {'code': 'kg', 'nicename': 'Kyrgyzstan', 'phonecode': 996, 'id': 114},
  {'code': 'la', 'nicename': 'Lao People\'\'s Democratic Republic', 'phonecode': 856, 'id': 115},
  {'code': 'lv', 'nicename': 'Latvia', 'phonecode': 371, 'id': 116},
  {'code': 'lb', 'nicename': 'Lebanon', 'phonecode': 961, 'id': 117},
  {'code': 'ls', 'nicename': 'Lesotho', 'phonecode': 266, 'id': 118},
  {'code': 'lr', 'nicename': 'Liberia', 'phonecode': 231, 'id': 119},
  {'code': 'ly', 'nicename': 'Libyan Arab Jamahiriya', 'phonecode': 218, 'id': 120},
  {'code': 'li', 'nicename': 'Liechtenstein', 'phonecode': 423, 'id': 121},
  {'code': 'lt', 'nicename': 'Lithuania', 'phonecode': 370, 'id': 122},
  {'code': 'lu', 'nicename': 'Luxembourg', 'phonecode': 352, 'id': 123},
  {'code': 'mo', 'nicename': 'Macao', 'phonecode': 853, 'id': 124},
  {'code': 'mk', 'nicename': 'Macedonia, the Former Yugoslav Republic of', 'phonecode': 389, 'id': 125},
  {'code': 'mg', 'nicename': 'Madagascar', 'phonecode': 261, 'id': 126},
  {'code': 'mw', 'nicename': 'Malawi', 'phonecode': 265, 'id': 127},
  {'code': 'my', 'nicename': 'Malaysia', 'phonecode': 60, 'id': 128},
  {'code': 'mv', 'nicename': 'Maldives', 'phonecode': 960, 'id': 129},
  {'code': 'ml', 'nicename': 'Mali', 'phonecode': 223, 'id': 130},
  {'code': 'mt', 'nicename': 'Malta', 'phonecode': 356, 'id': 131},
  {'code': 'mh', 'nicename': 'Marshall Islands', 'phonecode': 692, 'id': 132},
  {'code': 'mq', 'nicename': 'Martinique', 'phonecode': 596, 'id': 133},
  {'code': 'mr', 'nicename': 'Mauritania', 'phonecode': 222, 'id': 134},
  {'code': 'mu', 'nicename': 'Mauritius', 'phonecode': 230, 'id': 135},
  {'code': 'yt', 'nicename': 'Mayotte', 'phonecode': 269, 'id': 136},
  {'code': 'mx', 'nicename': 'Mexico', 'phonecode': 52, 'id': 137},
  {'code': 'fm', 'nicename': 'Micronesia, Federated States of', 'phonecode': 691, 'id': 138},
  {'code': 'md', 'nicename': 'Moldova, Republic of', 'phonecode': 373, 'id': 139},
  {'code': 'mc', 'nicename': 'Monaco', 'phonecode': 377, 'id': 140},
  {'code': 'mn', 'nicename': 'Mongolia', 'phonecode': 976, 'id': 141},
  {'code': 'ms', 'nicename': 'Montserrat', 'phonecode': 1664, 'id': 142},
  {'code': 'ma', 'nicename': 'Morocco', 'phonecode': 212, 'id': 143},
  {'code': 'mz', 'nicename': 'Mozambique', 'phonecode': 258, 'id': 144},
  {'code': 'mm', 'nicename': 'Myanmar', 'phonecode': 95, 'id': 145},
  {'code': 'na', 'nicename': 'Namibia', 'phonecode': 264, 'id': 146},
  {'code': 'nr', 'nicename': 'Nauru', 'phonecode': 674, 'id': 147},
  {'code': 'np', 'nicename': 'Nepal', 'phonecode': 977, 'id': 148},
  {'code': 'nl', 'nicename': 'Netherlands', 'phonecode': 31, 'id': 149},
  {'code': 'an', 'nicename': 'Netherlands Antilles', 'phonecode': 599, 'id': 150},
  {'code': 'nc', 'nicename': 'New Caledonia', 'phonecode': 687, 'id': 151},
  {'code': 'nz', 'nicename': 'New Zealand', 'phonecode': 64, 'id': 152},
  {'code': 'ni', 'nicename': 'Nicaragua', 'phonecode': 505, 'id': 153},
  {'code': 'ne', 'nicename': 'Niger', 'phonecode': 227, 'id': 154},
  {'code': 'ng', 'nicename': 'Nigeria', 'phonecode': 234, 'id': 155},
  {'code': 'nu', 'nicename': 'Niue', 'phonecode': 683, 'id': 156},
  {'code': 'nf', 'nicename': 'Norfolk Island', 'phonecode': 672, 'id': 157},
  {'code': 'mp', 'nicename': 'Northern Mariana Islands', 'phonecode': 1670, 'id': 158},
  {'code': 'no', 'nicename': 'Norway', 'phonecode': 47, 'id': 159},
  {'code': 'om', 'nicename': 'Oman', 'phonecode': 968, 'id': 160},
  {'code': 'pk', 'nicename': 'Pakistan', 'phonecode': 92, 'id': 161},
  {'code': 'pw', 'nicename': 'Palau', 'phonecode': 680, 'id': 162},
  {'code': 'ps', 'nicename': 'Palestinian Territory, Occupied', 'phonecode': 970, 'id': 163},
  {'code': 'pa', 'nicename': 'Panama', 'phonecode': 507, 'id': 164},
  {'code': 'pg', 'nicename': 'Papua New Guinea', 'phonecode': 675, 'id': 165},
  {'code': 'py', 'nicename': 'Paraguay', 'phonecode': 595, 'id': 166},
  {'code': 'pe', 'nicename': 'Peru', 'phonecode': 51, 'id': 167},
  {'code': 'ph', 'nicename': 'Philippines', 'phonecode': 63, 'id': 168},
  {'code': 'pn', 'nicename': 'Pitcairn', 'phonecode': 0, 'id': 169},
  {'code': 'pl', 'nicename': 'Poland', 'phonecode': 48, 'id': 170},
  {'code': 'pt', 'nicename': 'Portugal', 'phonecode': 351, 'id': 171},
  {'code': 'pr', 'nicename': 'Puerto Rico', 'phonecode': 1787, 'id': 172},
  {'code': 'qa', 'nicename': 'Qatar', 'phonecode': 974, 'id': 173},
  {'code': 're', 'nicename': 'Reunion', 'phonecode': 262, 'id': 174},
  {'code': 'ro', 'nicename': 'Romania', 'phonecode': 40, 'id': 175},
  {'code': 'ru', 'nicename': 'Russian Federation', 'phonecode': 70, 'id': 176},
  {'code': 'rw', 'nicename': 'Rwanda', 'phonecode': 250, 'id': 177},
  {'code': 'sh', 'nicename': 'Saint Helena', 'phonecode': 290, 'id': 178},
  {'code': 'kn', 'nicename': 'Saint Kitts and Nevis', 'phonecode': 1869, 'id': 179},
  {'code': 'lc', 'nicename': 'Saint Lucia', 'phonecode': 1758, 'id': 180},
  {'code': 'pm', 'nicename': 'Saint Pierre and Miquelon', 'phonecode': 508, 'id': 181},
  {'code': 'vc', 'nicename': 'Saint Vincent and the Grenadines', 'phonecode': 1784, 'id': 182},
  {'code': 'ws', 'nicename': 'Samoa', 'phonecode': 684, 'id': 183},
  {'code': 'sm', 'nicename': 'San Marino', 'phonecode': 378, 'id': 184},
  {'code': 'st', 'nicename': 'Sao Tome and Principe', 'phonecode': 239, 'id': 185},
  {'code': 'sa', 'nicename': 'Saudi Arabia', 'phonecode': 966, 'id': 186},
  {'code': 'sn', 'nicename': 'Senegal', 'phonecode': 221, 'id': 187},
  {'code': 'cs', 'nicename': 'Serbia and Montenegro', 'phonecode': 381, 'id': 188},
  {'code': 'sc', 'nicename': 'Seychelles', 'phonecode': 248, 'id': 189},
  {'code': 'sl', 'nicename': 'Sierra Leone', 'phonecode': 232, 'id': 190},
  {'code': 'sg', 'nicename': 'Singapore', 'phonecode': 65, 'id': 191},
  {'code': 'sk', 'nicename': 'Slovakia', 'phonecode': 421, 'id': 192},
  {'code': 'si', 'nicename': 'Slovenia', 'phonecode': 386, 'id': 193},
  {'code': 'sb', 'nicename': 'Solomon Islands', 'phonecode': 677, 'id': 194},
  {'code': 'so', 'nicename': 'Somalia', 'phonecode': 252, 'id': 195},
  {'code': 'za', 'nicename': 'South Africa', 'phonecode': 27, 'id': 196},
  {'code': 'gs', 'nicename': 'South Georgia and the South Sandwich Islands', 'phonecode': 0, 'id': 197},
  {'code': 'es', 'nicename': 'Spain', 'phonecode': 34, 'id': 198},
  {'code': 'lk', 'nicename': 'Sri Lanka', 'phonecode': 94, 'id': 199},
  {'code': 'sd', 'nicename': 'Sudan', 'phonecode': 249, 'id': 200},
  {'code': 'sr', 'nicename': 'Suriname', 'phonecode': 597, 'id': 201},
  {'code': 'sj', 'nicename': 'Svalbard and Jan Mayen', 'phonecode': 47, 'id': 202},
  {'code': 'sz', 'nicename': 'Swaziland', 'phonecode': 268, 'id': 203},
  {'code': 'se', 'nicename': 'Sweden', 'phonecode': 46, 'id': 204},
  {'code': 'ch', 'nicename': 'Switzerland', 'phonecode': 41, 'id': 205},
  {'code': 'sy', 'nicename': 'Syrian Arab Republic', 'phonecode': 963, 'id': 206},
  {'code': 'tw', 'nicename': 'Taiwan, Province of China', 'phonecode': 886, 'id': 207},
  {'code': 'tj', 'nicename': 'Tajikistan', 'phonecode': 992, 'id': 208},
  {'code': 'tz', 'nicename': 'Tanzania, United Republic of', 'phonecode': 255, 'id': 209},
  {'code': 'th', 'nicename': 'Thailand', 'phonecode': 66, 'id': 210},
  {'code': 'tl', 'nicename': 'Timor-Leste', 'phonecode': 670, 'id': 211},
  {'code': 'tg', 'nicename': 'Togo', 'phonecode': 228, 'id': 212},
  {'code': 'tk', 'nicename': 'Tokelau', 'phonecode': 690, 'id': 213},
  {'code': 'to', 'nicename': 'Tonga', 'phonecode': 676, 'id': 214},
  {'code': 'tt', 'nicename': 'Trinidad and Tobago', 'phonecode': 1868, 'id': 215},
  {'code': 'tn', 'nicename': 'Tunisia', 'phonecode': 216, 'id': 216},
  {'code': 'tr', 'nicename': 'Turkey', 'phonecode': 90, 'id': 217},
  {'code': 'tm', 'nicename': 'Turkmenistan', 'phonecode': 7370, 'id': 218},
  {'code': 'tc', 'nicename': 'Turks and Caicos Islands', 'phonecode': 1649, 'id': 219},
  {'code': 'tv', 'nicename': 'Tuvalu', 'phonecode': 688, 'id': 220},
  {'code': 'ug', 'nicename': 'Uganda', 'phonecode': 256, 'id': 221},
  {'code': 'ua', 'nicename': 'Ukraine', 'phonecode': 380, 'id': 222},
  {'code': 'ae', 'nicename': 'United Arab Emirates', 'phonecode': 971, 'id': 223},
  {'code': 'gb', 'nicename': 'United Kingdom', 'phonecode': 44, 'id': 224},
  {'code': 'us', 'nicename': 'United States', 'phonecode': 1, 'id': 225},
  {'code': 'um', 'nicename': 'United States Minor Outlying Islands', 'phonecode': 1, 'id': 226},
  {'code': 'uy', 'nicename': 'Uruguay', 'phonecode': 598, 'id': 227},
  {'code': 'uz', 'nicename': 'Uzbekistan', 'phonecode': 998, 'id': 228},
  {'code': 'vu', 'nicename': 'Vanuatu', 'phonecode': 678, 'id': 229},
  {'code': 've', 'nicename': 'Venezuela', 'phonecode': 58, 'id': 230},
  {'code': 'vn', 'nicename': 'Viet Nam', 'phonecode': 84, 'id': 231},
  {'code': 'vg', 'nicename': 'Virgin Islands, British', 'phonecode': 1284, 'id': 232},
  {'code': 'vi', 'nicename': 'Virgin Islands, U.s.', 'phonecode': 1340, 'id': 233},
]
