# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-28 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RasaBotUserSession',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_id', models.CharField(db_index=True, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('message_id', models.CharField(max_length=200)),
                ('from_no', models.CharField(blank=True, max_length=100, null=True)),
                ('to_no', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
