# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 13:03
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('rasa_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasabotusersession',
            name='activity_track',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
