# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_settings', '0019_auto_20171111_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('callsid', models.CharField(db_index=True, max_length=40, unique=True)),
                ('recordingsid', models.CharField(blank=True, max_length=40, null=True)),
                ('transcriptionsid', models.CharField(blank=True, max_length=40, null=True)),
                ('from_caller_id', models.CharField(blank=True, max_length=20, null=True)),
                ('to_caller_id', models.CharField(blank=True, max_length=20, null=True)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('transcription_text', models.TextField(blank=True, null=True)),
                ('generalsettings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_settings.GeneralSettings')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
