# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-22 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_manager', '0008_auto_20170825_1254'),
        ('ratings_manager', '0002_remove_feedback_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calendar_manager.CalendarDb'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_given',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
