# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-21 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20170715_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='attendants',
            field=models.PositiveIntegerField(verbose_name='Attendants Number'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='Duration'),
        ),
    ]
