# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-08 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20170728_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='currency',
            field=models.SmallIntegerField(blank=True, choices=[(2, 'EUR'), (1, 'USD')], default=1, verbose_name='Currency'),
        ),
    ]
