# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 16:00
from __future__ import unicode_literals

from django.db import migrations


def up(apps, schema_editor):
    Service = apps.get_model('services', 'Service')
    GeneralSettings = apps.get_model('app_settings', 'GeneralSettings')
    Account = apps.get_model('authentication_user', 'Account')
    for gs in GeneralSettings.objects.all():  # loop through all clients and cleanup if there are non-default services
        Service.objects.filter(generalsettings=gs).delete()
        company_accounts = Account.objects.filter(generalsettings=gs)
        if company_accounts.count() == 0:
            continue
        try:
            provider = company_accounts.filter(is_root_user=True).get()
        except Account.DoesNotExist:
            provider = (
                    company_accounts.filter(is_admin=True).first()
                    or company_accounts.filter(is_provider=True).first()
            )
            provider.is_root_user = True
            provider.save()

        if provider:
            if not provider.is_provider:
                provider.is_provider = True
                provider.save()
            for name in ['New Patient', 'Returning Patient', ]:
                service = Service.objects.create(
                    generalsettings_id=provider.generalsettings_id, name=name, duration=30,
                    price=30,
                )
                provider.services.add(service)


def down(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0007_auto_20171011_0420'),
    ]

    operations = [
        migrations.RunPython(up, down),
    ]
