# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-15 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_set_create_default_services_per_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='services.Category', verbose_name='Category'),
        ),
    ]
