# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('username', models.CharField(default='Roma', max_length=255, verbose_name='Username')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Mail')),
                ('phone', models.CharField(blank=True, default='', max_length=25, verbose_name='Phone number')),
                ('mobile', models.CharField(blank=True, default='', max_length=25, verbose_name='Mobile number')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('zip_code', models.CharField(default='43701', max_length=5)),
                ('note', models.TextField(blank=True, null=True, verbose_name='User note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin ?')),
                ('token', models.CharField(default='', max_length=50, verbose_name='Restore token')),
                ('restore', models.BooleanField(default=False, verbose_name='Restore ?')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
