# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 08:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_provider',
            field=models.BooleanField(default=False, verbose_name='Provider ?'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_secretarie',
            field=models.BooleanField(default=False, verbose_name='Secretarie ?'),
        ),
        migrations.AddField(
            model_name='account',
            name='providers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Providers list'),
        ),
    ]
