# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('authentication_user', '0002_auto_20170629_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='services',
            field=models.ManyToManyField(blank=True, to='services.Service', verbose_name='User services'),
        ),
    ]
