# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-06 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_user', '0003_account_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_customers',
            field=models.BooleanField(default=False, verbose_name='Customers ?'),
        ),
    ]
