# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-15 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_user', '0005_auto_20170714_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='mobile',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Mobile number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='token',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Restore token'),
        ),
        migrations.AlterField(
            model_name='account',
            name='zip_code',
            field=models.CharField(default='43701', max_length=5, null=True),
        ),
    ]
