# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_user', '0008_auto_20170722_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='token',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Restore token'),
        ),
    ]
