# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_user', '0009_auto_20170724_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='send_notification',
            field=models.BooleanField(default=True),
        ),
    ]
