# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 05:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_user', '0010_account_send_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='send_notification',
            new_name='receive_notification',
        ),
    ]
