# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-26 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_user', '0011_auto_20170727_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='', max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(default='', max_length=25, verbose_name='Phone number'),
        ),
    ]
