# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-27 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_user', '0012_auto_20170926_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mobile',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(default='', max_length=25, verbose_name='Mobile phone'),
        ),
    ]
