# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-06 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0011_create_initial_settings'),
        ('authentication_user', '0013_auto_20170927_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='generalsettings',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='app_settings.GeneralSettings'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='is_root_user',
            field=models.BooleanField(default=False, verbose_name='Root user ?'),
        ),
    ]
