# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-07 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_user', '0015_confirmationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='generalsettings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_settings.GeneralSettings'),
        ),
    ]
