# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-11 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_user', '0020_auto_20171111_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='has_subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
