# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_user', '0021_account_has_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='has_subscribed',
        ),
        migrations.AddField(
            model_name='account',
            name='email_subscription_status',
            field=models.CharField(choices=[('subscribed', 'Subscribed'), ('unsubscribed', 'Un-Subscribed'), ('bounced', 'Email Bounced and unlisted'), ('complained', 'Complained and unlisted')], default='subscribed', editable=False, max_length=100),
        ),
    ]
