# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_user', '0022_auto_20171124_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='region_code',
            field=models.CharField(default='US', max_length=2),
        ),
    ]
