# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-02 16:50
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Count


def up(apps, schema_editor):
    Account = apps.get_model('authentication_user', 'Account')
    dups = (Account.objects.values('phone', 'generalsettings_id')
            .annotate(Count('id'))
            .order_by()
            .filter(id__count__gt=1)
            .values_list('phone', flat=True))
    for phone in dups:
        if phone:
            qs = Account.objects.filter(phone=phone)
            keep = qs.first()
            qs.exclude(id=keep.id).delete()
    Account.objects.filter(phone='').update(phone=None)


def down(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('authentication_user', '0023_account_region_code'),
    ]

    operations = [
        migrations.RunPython(up, down),
    ]
