# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-02 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0021_auto_20180302_1019'),
        ('authentication_user', '0024_clean_duplicate_phone_number_peraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='It should be filled if this is customer account', max_length=254, null=True, verbose_name='Customer Mail ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, help_text='Used as unique ID/login ID for the account users/service providers', max_length=254, null=True, unique=True, verbose_name='Mail'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([
                ('generalsettings', 'phone'),
                ('generalsettings', 'customer_email')]),
        ),
    ]
