# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-09 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_user', '0025_auto_20180302_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, help_text='Used as unique ID/login ID for the account users/service providers', max_length=254, null=True, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='password'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='account',
            name='customer_email',
        ),
    ]
