# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-10 05:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0021_auto_20180302_1019'),
        ('authentication_user', '0026_auto_20180309_1126'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('generalsettings', 'email'), ('generalsettings', 'phone', 'country_code'), ('email', 'password')]),
        ),
    ]
