# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-26 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0024_cancellationsettings_reschedulingsettings'),
        ('authentication_user', '0027_auto_20180310_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.NullBooleanField(verbose_name='Active ?'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('generalsettings', 'phone', 'country_code'), ('generalsettings', 'email'), ('email', 'is_active')]),
        ),
    ]
