# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-03 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_user', '0029_auto_20180520_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='other_phones',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), default=list, max_length=420, size=None),
        ),
    ]
