# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-09 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_user', '0031_auto_20180604_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('authentication_user.account',),
        ),
        migrations.CreateModel(
            name='ProviderAccount',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('authentication_user.account',),
        ),
    ]
