# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-05 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_user', '0035_auto_20180701_0409'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([]),
        ),
    ]
