# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-08 05:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0025_twilioaccount'),
        ('authentication_user', '0036_auto_20180705_0936'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('generalsettings', 'phone', 'country_code'), ('generalsettings', 'email'), ('email', 'is_active')]),
        ),
    ]
