# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_user', '0039_account_hash_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='hash_key',
        ),
    ]
