# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-21 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_user', '0042_remove_account_ustimezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email1',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
