# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 10:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_manager', '0003_auto_20170706_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendardb',
            name='users_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User provider+', to=settings.AUTH_USER_MODEL, verbose_name='User provider'),
        ),
    ]
