# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-05 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_manager', '0006_auto_20170803_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendardb',
            name='remember',
            field=models.BooleanField(default=False),
        ),
    ]
