# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-25 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_manager', '0007_calendardb_remember'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendardb',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendardb',
            name='rate',
            field=models.CharField(choices=[('very_bad', 'very bad'), ('bad', 'bad'), ('normal', 'normal'), ('good', 'good'), ('very_good', 'very good')], default='normal', max_length=30),
        ),
    ]
