# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-26 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0016_auto_20171018_1015'),
        ('calendar_manager', '0008_auto_20170825_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendardb',
            name='generalsettings',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_settings.GeneralSettings'),
        ),
    ]
