# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-06 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_manager', '0009_calendardb_generalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendardb',
            name='google_calendar_event_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
