# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_manager', '0011_auto_20171119_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendardb',
            name='sent_feedback_mail',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
