# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-16 09:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_manager', '0013_auto_20180415_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendardb',
            name='users_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User customer+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calendardb',
            name='users_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User provider+', to=settings.AUTH_USER_MODEL, verbose_name='User provider'),
        ),
    ]
