# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-23 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_manager', '0014_auto_20180416_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendardb',
            name='google_calendar_event_id',
            field=models.CharField(db_index=True, max_length=80, null=True),
        ),
    ]
