# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-22 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_manager', '0015_calendardb_google_calendar_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendardb',
            name='old_start_times',
            field=django_mysql.models.ListCharField(models.CharField(max_length=40), default=list, max_length=410, size=None),
        ),
    ]
