# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 13:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breaks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(7, 'Sunday'), (6, 'Saturday'), (5, 'Friday'), (4, 'Thursday'), (3, 'Wednesday'), (2, 'Tuesday'), (1, 'Monday')], default=1, verbose_name='Day week')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': '2. Breaks',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=True)),
                ('day', models.PositiveSmallIntegerField(choices=[(7, 'Sunday'), (6, 'Saturday'), (5, 'Friday'), (4, 'Thursday'), (3, 'Wednesday'), (2, 'Tuesday'), (1, 'Monday')], default=1, verbose_name='Day week')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': '1. WorkingPlan',
                'ordering': ['-id'],
            },
        ),
    ]
