# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_link', models.URLField(blank=True, null=True)),
                ('google_analytics_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date_format', models.CharField(blank=True, max_length=255, null=True)),
                ('send_notification', models.BooleanField(default=False)),
                ('captcha', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '1. GeneralSettings',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='breaks',
            options={'ordering': ['-id'], 'verbose_name': '3. Breaks'},
        ),
        migrations.AlterModelOptions(
            name='workingplan',
            options={'ordering': ['-id'], 'verbose_name': '2. WorkingPlan'},
        ),
    ]
