# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 12:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_settings', '0002_auto_20170724_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(max_length=500)),
                ('email_body', models.TextField()),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_settings_initialconfirmation_related', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': '4. InitialConfirmation',
                'ordering': ['-id'],
            },
        ),
    ]
