# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 10:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0005_auto_20170725_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
