# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-21 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0006_auto_20170725_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send', models.BooleanField(default=True)),
                ('send_time', models.PositiveSmallIntegerField(default=4, help_text='in hours')),
            ],
            options={
                'verbose_name': '6. Feedback mail setting',
                'ordering': ['-id'],
            },
        ),
    ]
