# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-21 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0007_feedbackconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackconfig',
            name='send_time',
            field=models.FloatField(default=4, help_text='in hours'),
        ),
    ]
