# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-22 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0008_auto_20170921_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackconfig',
            name='google_rateus_link',
            field=models.URLField(default='google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedbackconfig',
            name='yelp_rateus_link',
            field=models.URLField(default='https://www.yelp.com/writeareview'),
            preserve_default=False,
        ),
    ]
