# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-11 17:50
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0012_auto_20171011_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['company_name', 'company_link', 'id']),
        ),
    ]
