# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-18 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0015_auto_20171015_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackconfig',
            name='generalsettings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_settings.GeneralSettings'),
        ),
        migrations.AlterField(
            model_name='initialconfirmation',
            name='generalsettings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_settings.GeneralSettings'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='generalsettings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_settings.GeneralSettings'),
        ),
    ]
