# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-02 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0016_auto_20171018_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackconfig',
            name='email_subject_tmpl',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='feedbackconfig',
            name='email_tmpl',
            field=models.TextField(),
        ),
    ]
