# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 07:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0019_auto_20171111_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackconfig',
            name='send_time_in_delta',
            field=models.DurationField(default=datetime.timedelta(0, 14400), editable=False),
        ),
    ]
