# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-02 15:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0020_feedbackconfig_send_time_in_delta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialconfirmation',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='app_settings_initialconfirmation_related', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
