# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-16 09:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0021_auto_20180302_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
