# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-23 13:38
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0022_auto_20180416_0528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackconfig',
            options={'ordering': ['-id'], 'verbose_name': '6. Feedback mail settings'},
        ),
        migrations.RenameField(
            model_name='feedbackconfig',
            old_name='email_tmpl',
            new_name='email_body',
        ),
        migrations.RenameField(
            model_name='feedbackconfig',
            old_name='email_subject_tmpl',
            new_name='email_subject',
        ),
        migrations.AddField(
            model_name='feedbackconfig',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedbackconfig',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='initialconfirmation',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initialconfirmation',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
