# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-28 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0024_cancellationsettings_reschedulingsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=250)),
                ('booked_fusion_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Booked Fusion Number')),
                ('generalsettings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_settings.GeneralSettings')),
            ],
        ),
    ]
