# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-29 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0025_twilioaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='twilioaccount',
            name='account_sid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='twilioaccount',
            name='auth_token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='twilioaccount',
            name='service_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
