# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-03 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0026_auto_20190329_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='twilioaccount',
            name='api_key',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='twilioaccount',
            name='api_key_secret',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
